# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Mcaps'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment sub create --location westeurope --template-file ./src/bicep/storageAccountSample/main.bicep --parameters deploymentName=mkpplntst'